apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: icgroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: asommer1/ic-webapp:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: icgroup
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: webapp
